//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReactTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int id { get; set; }
        public string caption { get; set; }
        public string description { get; set; }
        public string imageUrl { get; set; }
        public Nullable<bool> published { get; set; }
        public string createdBy { get; set; }
    }
}
