//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReactTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategoryMaster
    {
        public int SubCatId { get; set; }
        public Nullable<int> CatId { get; set; }
        public string SubCateName { get; set; }
    }
}
